codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 5
  round: down
  range: "85...100"

  status:
    project:
      default: off
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
  require_head: yes
  require_changes: no
